# Generated by Django 3.2 on 2022-11-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='myid',
        ),
    ]
